### PR TITLE
Update resource group name - Lab 02 - Exercise 3

### PR DESCRIPTION
**Pull request by lahmud**
## Location

- Course: AZ203
- Exercise: 03
- Task: 01
- Step[s]: 01

# Proposed Changes

- Correcting the resource group name that is used in the creation of the function app to be consistent with the rest of the instructions.

### CODE REVIEW

**Comment by tiagocostapt** [comment]
you can't reuse the same Resource group. First you create an App Service plan in Linux and this one is on Windows. It's not possible to have 2 App Service Plans with difference OS in the same RG. 
I had submitted a PR to update this lab today. We need to create a new RG and not reuse an existing one because it's only going to be used in the Function App.

**Comment by molenaar** [comment]
I already mentioned this in issue #106. The default service plan option is change to Linux causing this trouble.

**Comment by lahmud** [comment]
@tiagocostapt Thanks. Took your feedback and updated the documentation further in the page that references the new resource group name.

**Comment by seesharprun** [comment]
This lab has been updated so that all App Service components (2 Web Apps and Function App) uses Linux-based plans negating the need to use two resource groups.

The updated lab is here: b4400451766d265d2f6b0403e02e1a66cd387da5

**Pull request closed without merging**
