### PR TITLE
Update AZ-203_05_lab_ak.md

### PR DESCRIPTION
**Pull request by jakemcguire**
## Location

- Course: 05
- Exercise: 02
- Task: 02
- Step[s]: 4 and 6

# Proposed Changes

- Version_2_2 is deprecated and throws a warning during build, updating to Version_3_0 as recommended (cc: @mike11stevens)

### CODE REVIEW

**Comment by seesharprun** [comment]
Two items:

1.    If we make a change like this, it would need to occur in both the LAK and student guide. Changing in only one location creates a mismatch in the instructions. I updated your PR to reflect this.
1.    The lab environment (ALH) only supports 2.2 for a compatibility version. The lab VM is "frozen in time" and uses .NET 2.2.  You are seeing a build error because you are likely working in another environment or on your local machine. If you tried to switch to 3.0 in the lab VM, you will get a compilation error due to that not existing at the time the VM was built.

I have to make sure the lab works in the lab environment so I will close this PR. You are more than welcome to instruct your course attendees to switch to 3.0 if they run the labs locally.

**Comment by mike11stevens** [comment]
got it. will continue to advise learners to run labs locally w\ latest and supported versions of .NET Core

**Comment by seesharprun** [comment]
I don't think asking students to run labs locally using .NET Core 3.0 adds any value to the labs, even though many MCTs are doing that. If anything, that adds complexity and even more lab instructions that will need to be changed. For example, one of the labs in this course requires you to create an asynchronous entry point by "pinning" the C# language version to 7.1. If you are running in a .NET 3.0 environment, you would need to fix that too.

## How do we pick what version of .NET to use for the labs?

We try to use the latest long-term support (LTS) version of .NET with each course. When these labs were last updated, .NET Core 2.1 was the latest LTS version of .NET.

.NET Core 3.1 (not 3.0) is the latest LTS version and AZ-204's labs will launch on day 0 supporting .NET Core 3.1. We waited until 3.x had an LTS version before updating the labs.

## Why don't you always just skip ahead to the latest version?

2 reasons, it makes the labs harder to maintain and it narrows the audience too much.

First, if we updated the labs every time Microsoft released a minor update to .NET, we would never finish writing the labs. We had to stick a flag in the ground somewhere and say "only LTS releases". We also have to maintain the lab VM and it's easier to plan updates of the lab VM with every ALH based on a known date and that's the LTS release of .NET. The .NET team publicizes LTS dates months in advance.

Second, if you always updated every lab to use the latest .NET you would narrow your audience too much. For example, .NET 3.1 is a LTS release and its safe to say that many people are already using it. Technically, .NET 5 has a few [alpha builds](https://github.com/dotnet/core-sdk#installers-and-binaries) floating around. If I updated the labs to use the .NET 5, I would make the labs inaccessible to students who haven't learned the latest bits. .NET 6 is the next LTS version and it will release in November of 2021.

Many enterprises only update software when they are longly supported versions such as LTS. Now that .NET 3.1 is out, we can feel confident that enterprises will adopt it because of its LTS status and more students will come into the classroom knowing it. Remember this is an Azure development class, not a C# class.

**Comment by seesharprun** [comment]
If this helps, here is the release timeline for .NET

image

**Pull request closed without merging**
