### PR TITLE
Enable syntax highlight in Instructions code blocks

### PR DESCRIPTION
**Pull request by PeterDaveHello**
This will help improve the readability of the code blocks ;)

### CODE REVIEW

**Comment by seesharprun** [comment]
We are going to test this Markdown to make sure it doesn't impact the DOCX file generation. From a quick glance, the changes look good.

**Comment by PeterDaveHello** [comment]
Cool, is there anything I can do here?

**Comment by seesharprun** [comment]
I just ran ``pandoc --list-highlight-languages`` locally to get the list of languages.

I'm also checking other language shortcuts such as ``sh`` and ``dockerfile``.

**Comment by seesharprun** [comment]
The tricky thing is to figure out what syntax highlighting aliases are available on both GitHub Pages and Pandoc. I think I figured it out by comparing the output from Pandoc with this page: (https://github.com/github/linguist/blob/master/lib/linguist/languages.yml)

So here's what you need to do, you need to make the following replacements:

| Original syntax alias | Correct syntax alias |
| --- | --- |
| ``sh`` | ``bash`` |
| ``csharp`` | ``cs`` |

| Working aliases |
| --- |
| ``powershell`` |
| ``dockerfile`` |
| ``json`` |
| ``xml`` |
| ``sql`` |

**Comment by seesharprun** [comment]
I just sent you a PR where I make the code block changes.

**Comment by PeterDaveHello** [comment]
I directly updated the commit, see if it works ;)

**Pull request merged**
