### PR TITLE
Update the name of Cosmos DB query blade

### PR DESCRIPTION
**Pull request by eprigorodov**
At present moment (2019-11-06) there us no blade named "Query editor" in the Cosmos DB interface, the blade with similar functionality is called "Query Explorer".

## Location

- Course: 00
- Exercise: 00
- Task: 00
- Step[s]: 00

# Proposed Changes

-
-
-

### CODE REVIEW

**Comment by seesharprun** [comment]
I will need to update the lab to point to the Data Explorer instead of the Query Explorer

**Comment by eprigorodov** [comment]
Agreed, there is a warning that "Query Explorer" blade is going to be retired soon. Then the next step 4.  should better contain "New SQL Query" capitalized as in the actual button label:

> 4. Create a New SQL Query tab within the context of the Retail database and Online container. 

Would you like me to change the commit or will you fix that during the merge? Thanks!

**Comment by seesharprun** [comment]
I’m pushing fixes as part of my update early next week. Since this includes rewriting several steps, I can handle it.

**Comment by seesharprun** [comment]
I had to rework some of the branches, but your changes were included in the latest version of the lab instructions.

**Pull request closed without merging**
